/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_xausky_bh3modmanager_FusionZip */

#ifndef _Included_io_github_xausky_bh3modmanager_FusionZip
#define _Included_io_github_xausky_bh3modmanager_FusionZip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_xausky_bh3modmanager_FusionZip
 * Method:    patchZip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_io_github_xausky_bh3modmanager_FusionZip_patchZip
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
