/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_xausky_unitymodmanager_utils_NativeUtils */

#ifndef _Included_io_github_xausky_unitymodmanager_utils_NativeUtils
#define _Included_io_github_xausky_unitymodmanager_utils_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_OK
#define io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_OK 0L
#undef io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_INTERNAL_ERROR
#define io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_INTERNAL_ERROR -1L
#undef io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_PASSWORD_ERROR
#define io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_PASSWORD_ERROR -2L
#undef io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_FILE_CONFLICT
#define io_github_xausky_unitymodmanager_utils_NativeUtils_RESULT_STATE_FILE_CONFLICT -3L
/*
 * Class:     io_github_xausky_unitymodmanager_utils_NativeUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_xausky_unitymodmanager_utils_NativeUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
