/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_xausky_bh3modmanager_ZipUtils */

#ifndef _Included_io_github_xausky_bh3modmanager_ZipUtils
#define _Included_io_github_xausky_bh3modmanager_ZipUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_xausky_bh3modmanager_ZipUtils
 * Method:    unzipFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_xausky_bh3modmanager_ZipUtils_unzipFile
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
